title: MICCAI-FAIMI
email: dmoyer@csail.mit.edu
author: Aasa Feragen, Andrew King, Ben Glocker, Daniel Moyer, Enzo Ferrante, Eike Petersen, Melanie Ganz-Benjaminsen
baseurl: ""
description: >- # this means to ignore newlines until "lsi:"
  Website for the MICCAI Fairness in AI and Medical Imaging Tutorial

#lsi: false
safe: true
# source: 

theme: jekyll-theme-cayman

# Google services
# google_analytics: XX-00000000-0
# google_verification:

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  auto_ids:       true
  math_engine: mathjax
  syntax_highlighter: rouge
  
plugins_dir:
  - jekyll-sitemap
  - jekyll-seo-tag

#  - jekyll-remote-theme # add this line to the plugins list if you already have one
#remote_theme: pages-themes/cayman@v0.2.0
#plugins:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
